# Generated by Django 3.0.8 on 2020-07-29 05:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=500)),
                ('color', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='', max_length=40)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=40), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='HotKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=40)),
                ('nowCount', models.IntegerField(default=0)),
                ('prevCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserSearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=40)),
                ('word', models.CharField(default='', max_length=40)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserOutfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_tag', models.CharField(default='', max_length=400)),
                ('comment', models.CharField(default='', max_length=400)),
                ('bottom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bottom', to='fitzme.Garment')),
                ('dress', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dress', to='fitzme.Garment')),
                ('outer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='outer', to='fitzme.Garment')),
                ('shoes', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shoes', to='fitzme.Garment')),
                ('top', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='top', to='fitzme.Garment')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('nickname', models.CharField(max_length=12)),
                ('like_log_id', models.IntegerField(default=0)),
                ('isShow', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_outfit', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_outfit', to='fitzme.UserOutfit')),
            ],
        ),
    ]
