# Generated by Django 3.0.8 on 2020-08-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useroutfit',
            name='comment',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='useroutfit',
            name='hash_tag',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
