# Generated by Django 3.0.8 on 2020-08-01 19:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzme', '0002_auto_20200801_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='style_tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=40), blank=True, null=True, size=None),
        ),
    ]
