# Generated by Django 3.0.8 on 2020-08-01 22:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitzme', '0003_feed_style_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='garment',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='garment',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='garment',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=40, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='garment',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
